- name: '{{ stack_stat }} security group to allow incoming ssh connection'
  ec2_group:
    name: linux-security-group
    description: allow-ssh-http-from-anywhere
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    state: "{{ state }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
