- name: '{{ stack_stat }} service for {{ ecs.app_name }}'
  ecs_service:
    state: "{{ state }}"
    region: "{{ region }}"
    name: '{{ ecs.app_name + "-service" }}'
    cluster: "{{ ecs.cluster_name }}"
    task_definition: '{{ ecs.app_name }}'
    desired_count: 1
    delay: 100
  register: ecs_service_output
